### ISSUE TITLE
Random access rendering problem

### ISSUE THREAD

**Issue by MeloJR** [PolymerElements/iron-list#381] opened 2017-01-23 13:04 UTC
### Description
Hello! I have tried to use this element in an app I am building but I have found some problems. I have two views, one contains a **grid** of objects (rendered by an `iron-list` with padding-top and scroll target  = document); the other presents the object details.
If I try to keep the scroll position when navigating between different views, the iron-list is not rendering the first rows well.

I have done some tests and code inspection and, at first, I thought the cause of the problem was the padding top of the iron-list. However, I think that the main problem is the rendering when a random access occurs (lines 805-810 of `iron-list.html`). It happens if you refresh the page and keep the scroll position when you go back from the detail view.

### Expected outcome
The elements are displayed correctly as if you had scrolled to that position manually.

### Actual outcome
Some elements on the first rows are not displaying correctly:

![captura2](https://cloud.githubusercontent.com/assets/5193005/22203646/614dcefe-e16e-11e6-94ec-69bf30276600.PNG)

### Live Demo
https://elements.polymer-project.org/bower_components/iron-list/demo/grid.html

### Steps to reproduce
1. Open the console
2. Execute `window.scroll(0, 5000)`

### Browsers Affected
I have only tested the checked navigators. I have not tried with any of the unchecked ones
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [ ] IE 10
- [x] IE 11

**Comment by blasten** [comment] 2017-01-23 18:26
Yep. I fixed this one in the `2.0-preview` branch.

**Comment by MeloJR** [comment] 2017-01-24 10:25
Is there any way to fix it for polymer 1.7?

**Comment by keanulee** [comment] 2017-01-27 22:11
I think I found where the problem is - for random access, `_scrollHandler` [tries to increase](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L830) `_virtualStart` to a multiple of `_itemsPerRow` (in the example given above, `_virtualStart += 64`), but `_virtualStart` [is clamped by the difference between physical and virtual counts](https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L622) (which, when initial `_physicalCount` is 41, `_maxVirtualStart` is 59).

**Comment by blasten** [comment] 2017-01-28 00:27
Thanks for giving it a 👀 @keanulee.  One thing that I found is that the constraint `isClientFull` fails in `grid` mode because as soon as it hits a cell in row it assumes that the cell is the first cell in the row or the last cell in the row. Something like this might fix it:

```js
 var isClientFull = (this._physicalBottom + this._scrollOffset - 1 >= this._scrollBottom || this._virtualEnd === this._virtualCount) &&
          (this._physicalTop - this._scrollOffset - 1 <= this._scrollPosition || this._virtualStart === 0);
```
but it isn't very clear.

**Comment by blasten** [comment] 2017-02-25 02:48
@keanulee would you want to move [this code](https://github.com/PolymerElements/iron-list/commit/1008038e44c69f44495e44315e87d30088127692) + test to #master, so we can close this issue?

**Closed** 2017-02-28 01:19 UTC
