### ISSUE TITLE
Parent attribute ignored when child elements are stamped out.

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#75] opened 2015-08-22 23:52 UTC
I have a Polymer property whose value does not propagate to iron-list child elements when they are initially created.  Instead, the child elements initially reflects the default value for the property.  I cannot reproduce in the seed element, but it goes away when I copy/paste the element into a traditional ` <template is="dom-repeat">` element.

The property is set by adding an attribute to the parent element (`<easy-reg-manager disabled>`).  Here is the relevant Polymer code from the parent element:

```HTML
      <iron-list id="domain_list" height="40" style="overflow: scroll" items="{{_matching}}" as="domain" index-as="domain.domain">
        <template>
          <easy-reg-record
            class="row"
            search="[[_search]]"
            disabled="[[disabled]]"
            record="{{domain}}"
            >
          </easy-reg-record>
        </template>
      </iron-list>
```
```JavaScript
      disabled: {
        type: Boolean,
        value: false,
        notify: true
      },
```

If I manually flip the property value in the parent element using JS (`disabled = !disabled; disabled = !disabled;`) it will propagate down to the child element.  Here is the output from my browser's JS console:

```JavaScript
	 > EasyDNS.debug.reg_manager.disabled  //get current value
	 > true
	 > $('#items > easy-reg-record:nth-child(3)')[0].disabled //get current value
	 > false
	 > EasyDNS.debug.reg_manager.disabled = false
	 > false
	 > EasyDNS.debug.reg_manager.disabled = true
	 > true
	 > $('#items > easy-reg-record:nth-child(3)')[0].disabled
	 > true
```

I cannot reproduce the problem in a fresh seed-element, **but the problem goes away** when I use the traditional ` <template is="dom-repeat">`.  I'm using the latest version of Polymer (1.1.1), iron-list (1.0.3), and the WebComponentJS polyfill (0.7.12).  The issue persists across Chrome and Firefox.

Sadly, I can't just post the code publicly but I've <a href="https://www.youtube.com/watch?v=LWJTrxNOLQ4&feature=youtu.be">uploaded a video</a>.  If you don't see any obvious mistakes, I can share a gist of the relevant elements and a zip of the entire codebase.  Just contact me via email: zachlym@indolering.com.

**Comment by blasten** [comment] 2015-08-25 00:33
It seems to be a timing issue. I couldn't replicate this issue. Can you confirm when you set the initial value?

iron-list has a smoke test: https://github.com/PolymerElements/iron-list/blob/master/test/smoke/index.html that uses properties from outside the scope. 

I'd recommend trying to reduce the problem to just a few elements that I can test against.

**Comment by indolering** [comment] 2015-08-25 17:41
> It seems to be a timing issue. I couldn't replicate this issue. Can you confirm when you set the initial value?

When I set the initial value?  index.html has the parent element with the disabled attribute....

> I'd recommend trying to reduce the problem to just a few elements that I can test against.

So just turn off parts of the codebase until the problem goes away?  I figured that you had some way of observing the initialization process....

**Comment by blasten** [comment] 2015-08-25 23:02
what I mean by that: can you send a code that reflects the actual issue, so I can debug it.

**Comment by indolering** [comment] 2015-08-26 01:32
@blasten Yes, but I can't post it publicly. You can shoot me an email (zachlym@indolering.com) or send a PM on Slack.

**Comment by niflostancu** [comment] 2015-09-21 13:56
Hi,

I'm having a similar problem with properties outside the scope.
I reproduced this here: https://jsbin.com/goxohutadi/1/edit?html,output

If you uncomment the `items` value: 
```
items: {
   type: Array,
   value: function() { return []; }
},
```
The list behaves as expected. Also, if you type something in the input, the template updates the value for that property (`whyy`).
The problem only appears if the list initializes with an undefined `items` value.

Thanks.

**Comment by blasten** [comment] 2015-09-28 19:07
@indolering This issue should be fixed soon. https://github.com/PolymerElements/iron-list/issues/107

**Comment by blasten** [comment] 2015-10-09 19:40
@indolering This issue has been fixed. You can run `bower update` to update to the latest iron-list and Polymer.

**Closed by blasten** 2015-10-09 19:40 UTC
Labels: bug
