### ISSUE TITLE
Item selection in iron-list not working on IE11

### ISSUE THREAD

**Issue by Doncaster** [PolymerElements/iron-list#286] opened 2016-07-26 07:08 UTC
### Description
Selecting items from iron-list not working on IE11.
Bug appeared when Polymer version was changed from 1.2.3 -> 1.60. 
Iron-list version stayed at 1.3.4 the whole time.

### Expected outcome
When clicking item from iron-list with selection enabled, selection-changed event should be fired and the new item set as the current selection.

### Actual outcome
On IE11 nothing happens when item is clicked.

### Live Demo
https://jsbin.com/gisuqizagu/edit?html,console,output

### Steps to reproduce
1. Put iron-list element in the page
2. Add some items into the list
3. Set selection-enabled to the list
4. Click on an item in the list

### Browsers Affected
- [ ] IE 11

**Comment by nokawaii** [comment] 2016-08-16 11:01
Was looking if there actually such an issue exists while i was trying to fix a bug which occurs because of this behaviour... so what i wanted to say is, i can reproduce this issue with Polymer Version 1.5.0 and iron-list 1.3.4 in IE11.

Hope this gets fixed soon :)

**Comment by blasten** [comment] 2016-08-19 23:04
This is fixed in `v1.3.7`

**Closed by blasten** 2016-08-19 23:04 UTC

**Comment by timove** [comment] 2016-09-05 14:43
This seems to be broken using 1.3.7 locally or the live demo above using IE11. Shall I open a new issue?

**Comment by nokawaii** [comment] 2016-09-06 09:18
Yes. It actually does select now, but only the first child in the list-template.
If i do something like the following, and click on the span area for example, then the selection doesnt work:

`<iron-list id="itemsList" items="{{items}}" on-selected-item-changed="_doStuff" selection-enabled>
  <template>
    <div class="layout horizontal justified" data-is-selected-div="{{selected}}">
      <template is="dom-if" if="[[_isModel(item)]]">
        <div class="custom-paper-item project">
          <span>[[_computeItemName(item,locale)]]</span>
        </div>
        <div class="deleteButton">
          <paper-icon-button icon="fa:trash" hidden="{{!selected}}" disabled="{{!selected}}" on-tap="_toggleSecurityDialog"></paper-icon-button>
        </div>
      </template>
      <template is="dom-if" if="[[!_isModel(item)]]">
        <div class="custom-paper-item profile" disabled>
          <pre><span>[[locale.profile]]</span><span>[[item.name]]</span></pre>
        </div>
      </template>
    </div>
  </template>
</iron-list>`

**Comment by timove** [comment] 2016-09-06 13:56
Ah, ok, thanks @nokawaii. The JSBin example from @Doncaster was still using v1.3.5. I created another JSBin using the current v1.3.7 with a twist: the `div`s inside the iron-lists template are now within a `paper-item` element. 

Using IE11 the iron-list v1.3.7 does select the appropriate item when clicking the item outside the `div` but not when clicking the `div` inside it. [https://jsbin.com/zitoleyoji/1/edit?html,console,output](https://jsbin.com/zitoleyoji/1/edit?html,console,output)

Can this be due to the IE11 reporting the `activeElement` in `iron-list`'s `_selectionHandler` function to be the `div` instead of the `paper-item`?

**Comment by timove** [comment] 2016-09-08 15:16
I found a workaround for my use-case. Adding a style of `paper-item > * {pointer-events: none;}` prevents IE11 from reporting the `div` inside the `paper-item` as `activeElement`. See [https://jsbin.com/fujowokisa/1/edit?html,console,output](https://jsbin.com/fujowokisa/1/edit?html,console,output). Now the `div` can be clicked to select an item, because the underlying `paper-item` actually receives the event.

**Comment by nokawaii** [comment] 2016-09-13 07:55
Thanks a lot @timove. I'll try your solution and hopefully, it'll be fixed :)

**Comment by nokawaii** [comment] 2016-11-07 08:52
@timove your fix with the style works fine. I customized it a bit for my needs, but many thanks to you!
