### ISSUE TITLE
iron-list (grid layout) shift visible elements when tap on paper-menu-button menu inside an item

### ISSUE THREAD

**Issue by Eymerich01** [PolymerElements/iron-list#288] opened 2016-07-27 11:54 UTC
### Description

iron-list (grid layout) shift visible elements when tap on paper-menu-button  inside an item.
### Live Demo

https://jsbin.com/lozixipoke/edit?html,output
### Steps to reproduce

use scroll to go mid-list then tap on "more-vert" icon. you could see that iron-list shift items up almost a row.
### Browsers Affected

- [x] Chrome

**Comment by blasten** [comment] 2016-07-29 01:50
I can repro the issue. The problem is that in this case neon-animation fires the `iron-resize` event which triggers scroll update in iron-list. I would look into ways to avoid doing that sort of adjustments after resizes, but the quick workaround is to add the paper-menu outside the iron-list.

**Comment by rbjarnason** [comment] 2016-08-09 22:24
@blasten This also happen with iron-pages inside iron-list cards. Not sure what you mean by "add the" element outside iron-list. Shall I just not use iron-pages inside iron list templates or is there any other workaround?

**Comment by blasten** [comment] 2016-08-10 00:13
@rbjarnason Do you have a jsbin?

**Comment by rbjarnason** [comment] 2016-08-10 00:22
@blasten No, I've just replaced iron-pages with a simple hidden$ based solution and now everything works fine.  I'm on a deadline so don't have time to create a test case but the source code is here: https://github.com/rbjarnason/open-active-voting/blob/master/public/src/oav-area-ballot/oav-area-ballot-item.html#L158

**Comment by keanulee** [comment] 2017-03-08 22:49
This should be fixed by #346

**Closed by keanulee** 2017-03-08 22:49 UTC
Labels: enhancement
