### ISSUE TITLE
Problem with iron-list and paper-drawer-panel

### ISSUE THREAD

**Issue by Krazitchek** [PolymerElements/iron-list#27] opened 2015-07-15 17:23 UTC
Hello, i have a ```<paper-drawer-panel>``` with a ```<paper-header-panel drawer>``` for the side menu and a ```<paper-header-panel main>``` for the main window.

Inside ```<paper-header-panel main>``` i have a ```<paper-toolbar>```.

On this ```<paper-toolbar>``` i have a ```<paper-button>``` with an ```<iron-ajax>``` calling a form to display in ```div#content``` on click.

On load i have an ```<iron-list>``` (copy/paste from demo1.html on iron-list documentation) which loads a json file (the one from the documentation).

```
<paper-drawer-panel force-narrow drawer-width="270px">
	<paper-header-panel drawer>
	...
	</paper-header-panel>

	<paper-header-panel main>
		<paper-toolbar>
		... //ajax button here
		</paper-toolbar>

		<div id="content">
            <x-app></x-app> //json file load
        </div>
    </paper-header-panel>
</paper-drawer-panel>
```

OK, it works. If i load page, list (json file appear), if i click on the button (ajax request), the form appear.

But if refresh (reload page), and i use the scrollbar to go to the end of the list, and next, click on the button (ajax request to load the form), nothing happen, no error on console, nothing. If i click another time (so, second time), the form loads.

In that case, (refresh, bottom with scrollbar, click), i need to click twice to load the form.

Now, if i remove ```<paper-drawer-panel>```, like this:

```
	<paper-header-panel main>
		<paper-toolbar>
		... //ajax button here
		</paper-toolbar>

		<div id="content">
            <x-app></x-app> //json file load
        </div>
    </paper-header-panel>
```

I haven't the problem, i can do what i want, refresh, scroll, click, it's ok.

So, maybe there is something wrong with iron-list/iron-ajax/paper-drawer-panel ?!

**Comment by blasten** [comment] 2015-07-17 17:41
I have identified an issue when you scroll all the way to the bottom and then you reassign a new item set. Does the list look empty to you after you click `refresh`?   If scroll back up, the list picks up the new items and everything works as expected.

**Comment by Krazitchek** [comment] 2015-07-17 19:05
I just made another test, it seems i have the problem on Firefox (39), but not on Chromium (43).

On Firefox, i load page, go with scroll bar to the very bottom of the page, i have to click the button (form by ajax) twice to have the request working. On Chromium, only once, as expected.

Yes, if i refresh (reload page) the list from the json file is well loaded.

I have uploaded an example here: https://vps160745.ovh.net/polymer/

It's HTTPS and the certificate used is an autogenerated one (by me), so, you have to make a temporary exception to access the page.

The button used to load the form by ajax (iron-form) is the "+ New Op" button on the toolbar.

Another thing i just see is a blank area at the bottom of the list on Chromium which does not exist with the same page on firefox.

**Comment by blasten** [comment] 2015-07-17 21:50
@Krazitchek  can you try to update iron-list: `bower update polymerelements/iron-list#items-reset` and let me know if the issue is gone.

**Closed** 2015-07-17 23:59 UTC
Labels: rendering

**Comment by Krazitchek** [comment] 2015-07-18 06:59
bower update polymerelements/iron-list#items-reset:
bower                          ENOTINS Package polymerelements/iron-list#items-reset is not installed

bower install polymerelements/iron-list#items-reset:
bower iron-list#items-reset not-cached git://github.com/polymerelements/iron-list.git#items-reset
bower iron-list#items-reset    resolve git://github.com/polymerelements/iron-list.git#items-reset
bower iron-list#items-reset     ENORESTARGET Tag/branch items-reset does not exist

**Comment by Krazitchek** [comment] 2015-07-18 07:17
I just reset everything and do:

bower cache clean
bower install Polymer/polymer --production
bower install PolymerElements/iron-elements --production
bower install PolymerElements/paper-elements --production
bower install PolymerElements/neon-elements --production
bower install PolymerElements/gold-cc-expiration-input --production
bower install PolymerElements/gold-email-input --production
bower install PolymerElements/marked-element --production

And test again, but the issue is still here, and the blank area at the bottom of the page on Chromium too. Look at the screenshots please. Can you see the blank area ?


![chromium](https://cloud.githubusercontent.com/assets/11500208/8760746/06a67888-2cf3-11e5-9ea2-d482726dd46e.png)
![firefox](https://cloud.githubusercontent.com/assets/11500208/8760745/06a51222-2cf3-11e5-85a5-38aaf6b019af.png)

**Comment by blasten** [comment] 2015-07-24 17:41
@Krazitchek the blank area seems to be a layout issue. Your app should have the following:

1.  `<body class="fullbleed" unresolved>`
2. `<paper-header-panel class="fit">`
