### ISSUE TITLE
The _physicalCount never goes below its default value [20]

### ISSUE THREAD

**Issue by urandom** [PolymerElements/iron-list#55] opened 2015-08-09 08:36 UTC
If you have less than 20 virtual items, rather than rendering only that count, the list will happily render all 20 physical items, even though the rest don't have any backing data. The extreme case is even more apparent, when the item count is actually 0.

The problem with the extreme case is that the items don't even have a hidden attribute. They are plainly visible.

**Comment by blasten** [comment] 2015-08-10 18:46
This is by design, the list will always create at least 20 physical items. However, it will hide the physical items that don't have any backing data.  I couldn't replicate the issue you are describing:

e.g.
```html
<iron-list id="list" items="[]" as="item">
  <template>
    <div>[[index]]</div>
  </template>
</iron-list>
```

or programmatically:

```js
list.items = [];
```

All the physical items have the `hidden` attribute. Can you submit a jsbin that replicates the issue?

**Comment by urandom** [comment] 2015-08-11 09:21
_assignModels isn't getting called if the 'items' is null

I have no idea how to create a jsbin, so here's a modified demo file instead. You can see that the generated items do not have the hidden attribute. Also, the behavior is not observed if you switch on shadow dom.

```html
<!doctype html>
<html>
<head>

  <title>iron-list, paper-scroll-header-panel, filltext.com demo</title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1, user-scalable=yes">
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">

  <script src="../../webcomponentsjs/webcomponents-lite.js"></script>

  <link rel="import" href="../../polymer/polymer.html">

  <link rel="import" href="../../iron-flex-layout/iron-flex-layout.html">
  <link rel="import" href="../../paper-drawer-panel/paper-drawer-panel.html">
  <link rel="import" href="../../paper-toolbar/paper-toolbar.html">
  <link rel="import" href="../../paper-header-panel/paper-header-panel.html">
  <link rel="import" href="../../paper-spinner/paper-spinner.html">

  <link rel="import" href="../../paper-icon-button/paper-icon-button.html">
  <link rel="import" href="../../iron-ajax/iron-ajax.html">
  <link rel="import" href="../../iron-icons/iron-icons.html">

  <link rel="import" href="../iron-list.html">
</head>

<body unresolved>
  <dom-module id="rf-app-scaffold">
    <style>
paper-toolbar {
  font-size: 24px;
}

.content {
  padding: 8px 16px 16px;
  min-height: 5em;
  margin: 10px 120px 60px 5px;
  background-color: #f8f8f8 !important;
}

.narrow.content {
  padding-top: 16px;
  margin: 0px 0px 60px 0px;
}

[drawer] .menu-container {
  padding: 8px 0;
}

paper-header-panel[main] /deep/ .main-title-container {
  font-size: 24px;
}
    </style>
    <template>
      <paper-drawer-panel id="drawer" responsive-width="768px">
        <paper-header-panel drawer mode="standard">
          <paper-toolbar>
            <content select=".drawer-title"></content>
          </paper-toolbar>
          <div class="menu-container">
            <content select=".drawer-menu"></content>
          </div>
        </paper-header-panel>
        <paper-header-panel main mode="standard">
          <paper-toolbar>
            <paper-icon-button icon="menu" paper-drawer-toggle></paper-icon-button>
            <div class="main-narrow-title-container">
              <content select=".main-title"></content>
            </div>
          </paper-toolbar>
          <div class$="content card">
            <h1>The list</h1>
            <iron-list items="[[items]]" as="item">
              <template>
                <div style="min-height: 2em; min-width: 5em; background: red;" class="card">
                  <h1> TEST </h1>
                  <div class="item">
                    <div class="primary dim">[[item.index]]</div>
                    <div class="pad">
                      <div class="primary"><span>[[item.fname]]</span> <span>[[item.lname]]</span></div>
                      <div class="secondary"><span>[[item.address]]</span> <span>[[item.city]]</span></div>
                      <div class="secondary"><span>[[item.city]]</span>, <span>[[item.state]]</span>  <span>[[item.zip]]</span></div>
                      <div class="secondary dim">[[item.business]]</div>
                    </div>
                    <iron-icon icon$="[[iconForItem(item)]]"></iron-icon>
                  </div>
                </div>
              </template>
            </iron-list>
          </div>
        </paper-header-panel>
      </paper-drawer-panel>
    </template>
    <script>
"use strict";
Polymer({
  is: "rf-app-scaffold",
  properties: {
    items: Array,
  },

  attached: function() {
    this.async(function() {
      this.items = null;
    }.bind(this));
  },
})
    </script>
  </dom-module>

  <rf-app-scaffold>
    <div class="drawer-title">Drawer</div>
    <div class="main-title">Title</div>
  </rf-app-scaffold>
</body>
</html>
```

**Comment by blasten** [comment] 2015-08-11 17:23
@urandom I confirmed this issue. It should be fixed soon.

**Closed** 2015-08-11 22:28 UTC
Labels: bug

**Comment by Sinjins** [comment] 2015-08-18 18:50
Ran into this issue as well.  Particularly troublesome when the list item template contains a more complex custom element.  The iron-list seems to then 'ready' up to 19 extra custom element instances, if you happen to only pass it one array item.  This has a big impact on load time.

**Comment by Sinjins** [comment] 2015-08-21 16:24
@blasten is there a way to specify the value of `_physicalCount` property of the iron-list instance before it is rendered?  I'm not sure how I might access/set this iron-list property before the `ready` lifecycle callback of the iron-list's host element fires.  Refer to following SO issue if you prefer:  http://stackoverflow.com/questions/32080088/polymer-1-0-iron-list-loading-hidden-list-items/32128724#32128724

**Comment by blasten** [comment] 2015-08-21 17:13
@Sinjins  nop. I will try to reduce the initial value now that we have a feature that can increase the pool size of node elements.  The value `20` is a constant https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L133

**Comment by Sinjins** [comment] 2015-08-21 17:29
@blasten   I suppose, in the end, what I'm trying to do is use the iron-list element (and its associated features/CSS etc.), for a known fixed-length array of items.  Should I not use the iron-list element in that way?  Is it solely built to handle a variable-length array of items?

**Comment by blasten** [comment] 2015-08-21 17:42
@Sinjins that's right. I will recommend using a `dom-repeat`  here's why: https://github.com/PolymerElements/iron-list/issues/68
